<?php

/**
 * @author owliber <owliber@yahoo.com>
 * @date Apr 13, 2015
 * @filename index.php
 */

Yii::app()->clientScript->registerScript('ui','
    
    $(\'input[rel="tooltip"]\').tooltip();     
    /*   
    $("#generator").modal({
        backdrop: true,
        keyboard: true,
        show : false,
    }).css({
        width: "600px",
        "margin-left": function () {
            return -($(this).width() / 2);
        }
    });
    */
          
    $("#ajaxBtnGenerate").click(function(){
          var acct_type = $("#AccountCodesModel_account_type_id"),
                    qty = $("#AccountCodesModel_quantity");
                    
          if(qty.val() == "" || qty.val() == 0)
          {
            alert("Please enter positive number");
            return false;
          }
          else
          {
              if(qty.val() > 100)
              {
                alert("Quantity should not be greater than 100.");
                return false;
              }
              else
              {
                return true;
              }
          }
    });
    
 ', CClientScript::POS_END);
?>
<?php
$this->breadcrumbs = array('Admin'=>array('#'),'Account Code Batches'); ?>
 
<?php echo TbHtml::button('Generate Account Codes', array(
    'color' => TbHtml::BUTTON_COLOR_DANGER,
    'icon'=>  TbHtml::ICON_PLUS_SIGN,
    'data-toggle' => 'modal',
    'data-target' => '#generator',
    'style'=>'margin:20px 20px 0',
    'class'=>'pull-right',
)); ?>

<?php
Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_WARNING,
        '<h4>Account Code Batches</h4> Lists of generated account codes batches per account types.'
);
?>

<?php $this->widget('bootstrap.widgets.TbAlert', array(
    'block'=>true,
    'fade'=>true, // use transitions?
    'closeText'=>false,
)); ?>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
    'id'=>'code-batches-grid',
    'type'=>  TbHtml::GRID_TYPE_HOVER,
    'dataProvider'=>$dataProvider,
    'enablePagination' => true,
    'columns'=>array(
        array('name'=>'code_batch_id', 
                'header'=>'#',
                'htmlOptions'=>array('style'=>'text-align:center;'),
                'headerHtmlOptions' => array('style' => 'text-align:center'),
            ),
        array('name'=>'account_type_name', 
                'header'=>'Account Type',
                'htmlOptions'=>array('style'=>'text-align:center;'),
                'headerHtmlOptions' => array('style' => 'text-align:center'),
            ),
        array('name'=>'quantity', 
                'header'=>'Quantity',
                'htmlOptions'=>array('style'=>'text-align:center;'),
                'headerHtmlOptions' => array('style' => 'text-align:center'),
            ),
        array('name'=>'used', 
                'header'=>'Used',
                'htmlOptions'=>array('style'=>'text-align:center;'),
                'headerHtmlOptions' => array('style' => 'text-align:center'),
            ),
        array('name'=>'available', 
                'header'=>'Available',
                'htmlOptions'=>array('style'=>'text-align:center;'),
                'headerHtmlOptions' => array('style' => 'text-align:center'),
            ),
        array('name'=>'date_generated', 
                'header'=>'Date Generated',
                'htmlOptions'=>array('style'=>'text-align:center;'),
                'headerHtmlOptions' => array('style' => 'text-align:center'),
            ),
        array('name'=>'generated_by', 
                'header'=>'Generated By',
                'htmlOptions'=>array('style'=>'text-align:left'),
                'headerHtmlOptions' => array('style' => 'text-align:left'),
            ), 
        array('name'=>'generated_from_ip', 
                'header'=>'IP Address',
                'htmlOptions'=>array('style'=>'text-align:center'),
                'headerHtmlOptions' => array('style' => 'text-align:center'),
            ),
        array('class'=>'bootstrap.widgets.TbButtonColumn',
                'template'=>'{list}',
                'buttons'=>array
                (
                    'list'=>array
                    (
                        'label'=>'View Generated Code Lists',
                        'icon'=>  TbHtml::ICON_LIST,
                        'url'=>'Yii::app()->createUrl("/codes/index",array("id"=>$data["code_batch_id"],"account_type"=>$data["account_type_id"]))',
                        'options' => array(
                            'class'=>"btn btn-small",
                        ),
                        array('id' => 'send-link-'.uniqid())
                    ),
                ),
                'header'=>'Options',
                'htmlOptions'=>array('style'=>'width:80px;text-align:center'),
                'headerHtmlOptions'=>array('style'=>'text-align:center'),
            ),
    ),
)); ?>

<?php
    $this->widget('bootstrap.widgets.TbModal', array(
    'id' => 'generator',
    'header' => 'Generate Account Codes',
    'content' => $this->renderPartial('_form', array('model'=>$model), true),
    'footer'=>array(
        TbHtml::ajaxButton('Generate', 'generate', array(
            'data'=>array(
                'account_type_id'=>'js:function(){return $("#AccountCodesModel_account_type_id").val()}',
                'quantity'=>'js:function(){return $("#AccountCodesModel_quantity").val()}',
            ),
            'type' => 'GET',
            'dataType'=>'json',
            'success'=>'function(data){
                if(data.result_code == 1)
                {
                    alert(data.result_msg);
                }
                else
                {
                    $.fn.yiiGridView.update("code-batches-grid");
                    alert(data.result_msg);
                    $("#generator").modal("hide");
                }
            }',
        ), array(
            
            'color'=>  TbHtml::BUTTON_COLOR_PRIMARY,
            'confirm'=>'Are you sure you want to continue?',
            'id'=>'ajaxBtnGenerate',
        )),
        TbHtml::button('Close', array('data-dismiss' => 'modal')),
    ),
)); 